### ISSUE TITLE
`litdouble` fails on `INFINITY` and `NAN` values

### ISSUE THREAD

**Issue by RyanGlScott** [fdedden/language-c99-util#5]
```
$ cabal repl -b ieee754 -b language-c99-util
<snip>
λ> import Language.C99.Pretty (pretty)
λ> import Language.C99.Util (litdouble)
λ> import Numeric.IEEE (IEEE(..))
λ> pretty (litdouble infinity)
*** Exception: Can't translate an infinite floating point number:
CallStack (from HasCallStack):
  error, called at src/Language/C99/Util/Expr.hs:97:26 in language-c99-util-0.1.1-5c88c936679457490f9da31103e55d54f5b3e7222fb03697d5ac08b8412de52c:Language.C99.Util.Expr
λ> pretty (litdouble nan)
*** Exception: Prelude.tail: empty list
```

It seems like we could make `litdouble` a total function by having it generate the `INFINITY`/`NAN` macros as appropriate.

**Comment by fdedden** [comment]
I have added support for NaN, Infinity and -Infinity.

-NaN does not seem to be supported in Haskell (as per IEEE754), but it seems to exist in C99. With the current implementation there is no way to create -NaN.

```
ghci> nan :: Double
NaN
ghci> -nan :: Double
NaN
ghci> (-nan :: Double) < 0
False
```

**Comment by RyanGlScott** [comment]
Thanks! Would you be able to make a new Hackage release with these changes?

-----

For what it's worth, Haskell does track sign bits in NaN values, but the `printf` function from `Text.Printf` prints all NaN values as `NaN`, regardless of their sign bit. As far as I can tell, the only way to determine what the sign bit of a NaN value is in Haskell is to use the C FFI and call something like the `signbit` function. Unfortunately, the `ieee754` library doesn't provide `signbit` directly, although you can implement it in terms of `copysign`:

```hs
module Main (main) where

import Numeric.IEEE

-- | Returns 'True' if the sign bit is set.
signbit :: IEEE a => a -> Bool
signbit x = copySign 1 x == -1

main :: IO ()
main = do
  let n :: Double
      n = nanWithPayload 1
  print $ signbit n
  print $ signbit (-n)
```
```
λ> main
False
True
```

That being said, being able to distinguish the sign bit is only half the battle, as you'd also have to be able to determine the corresponding NaN value in C. Just writing `-NAN` or `NAN` wouldn't be sufficient, as the C99 standard makes no guarantee about what the sign bit of `NAN` is, as far as I can tell. (In fact, [`ieee754`'s `nan` can very well have a different sign bit than C's `NAN`](https://github.com/patperry/hs-ieee754/issues/20)!) I think the only way to ensure that the NaN value in C is the exact same is to create a NaN value with the same payload (similarly to how `ieee754` does it [here](https://github.com/patperry/hs-ieee754/blob/32ed20b21635e47ce50ffc90e10889f2d6d58caa/cbits/double.c#L89-L102)), but that requires some pretty non-portable-looking code.

This is all to say: trying to be more fine-grained with NaN values would be difficult in a pure C99 setting, and I think `language-c99-util`'s behavior here is reasonable.

**Comment by fdedden** [comment]
Thanks for the help and elaboration. It indeed seems that making a direct representation Haskell's `nan` in C is difficult. For now I will leave it as is.

I will publish these changes and some other as version 0.2.0.

**Comment by fdedden** [comment]
The new packages are published on hackage:
https://hackage.haskell.org/package/language-c99-0.2.0
https://hackage.haskell.org/package/language-c99-util-0.2.0
https://hackage.haskell.org/package/language-c99-simple-0.2.0

The plan is to have the next release of Copilot (3.10) depend on the new packages.

**Comment by RyanGlScott** [comment]
Thanks, @fdedden!
